### ISSUE TITLE
Redirect users to the page they came from entering login

### ISSUE THREAD

**Issue by wolfcomp** [Glimesh/glimesh.tv#182]

**Comment by Kjasi** [comment]
This would be very helpful with OAuth authorization when switching accounts. 

Currently, if I need to authorize my streamer account, I click the authorize button in my app, which brings me to the authorization page. But, if I'm logged in with the wrong account, I need to log out and back in. After doing so, I no longer have access to the authorization page, and have to hit my authentication button again to get back there.

**Comment by Eein** [comment]
using a 'redirect token' will save a world of hurt down the road for this

a redirect_plug can be useful here, but should provide a couple of checks:
1. Verify the domain passed into the redirect param
2. Base64 encode the redirect url - this is important so it doesn't conflict if the redirect has url params (avoids dealing with escaping and weird browser support - and 3rd party integrations)
3. store the token in session if its good
4. if authorization is complete, clear the redirect session key and redirect to the (decoded) token instead of the default path

In my experience this is good enough to handle all forms of auth flows, and makes redirects very easy to pass in wherever you need them

**Comment by clone1018** [comment]
This is implemented and in production.
