### ISSUE TITLE
Don't revoke subscription benefits until the end of a renewal period

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#365]

**Comment by shrink** [comment]
The system currently has a direct relationship between a Subscription to a channel, and a Stripe payment subscription. The cancellation of a Subscription to a channel immediately deletes the Stripe payment subscription.

https://github.com/Glimesh/glimesh.tv/blob/66e05f4b888938573bd77bdc0c3166442b2c72cf/lib/glimesh_web/live/platform_subscription_live/index.ex#L90-L95

https://github.com/Glimesh/glimesh.tv/blob/66e05f4b888938573bd77bdc0c3166442b2c72cf/lib/glimesh/payments.ex#L210-L213

Stripe supports an alternative approach: cancel the subscription at the end of the billing period, which is activated on a per-subscription basis by setting`cancel_at_period_end` to `true`. Then, at the end of the billing period, Stripe will cancel the subscription and the standard "cancelled subscription" webhook flow can proceed as-is.

Making this change would be straight forward: 

```diff
-   with {:ok, _} <- Stripe.Subscription.delete(subscription.stripe_subscription_id),
+   with {:ok, _} <- Stripe.Subscription.updatesubscription.stripe_subscription_id, %{cancel_at_period_end: true}),
```

However I think this raises an important question about the relationship between a Stripe payment subscription and a Subscription to a channel, and how Subscriptions are thought about. There are a couple of use-cases I can think of when it comes to subscribing:

1. I subscribe to my favourite channel on a recurring basis
2. I subscribe to a channel as a one-off
3. I gift one or more subscriptions
4. I cancel a Subscription and then decide to resume it during the remaining period
5. I want to cancel my subscription immediately and surrender the remaining time

And the current system describes a Subscription as:

* `is_active` boolean
* `started_at` datetime
* `ended_at` datetime

The current implementation supports the first use-case very well, but would require some degree of expectation-bending to support the latter. For example, a one-off Subscription _could_ be supported by immediately setting `cancel_at_period_end: true` but there's no way to represent that (using the properties above). We need to be able to answer the following questions:

a. is this subscription going to (attempt to) renew at the end of the current period?
b. when will the subscription attempt to renew?
c. has this subscription ended?

I think these properties would achieve that:

* `started_at` datetime
* `expires_at` datetime
* `is_renewing` boolean

1. I subscribe to my favourite channel on a recurring basis

```
started_at: 2020-01-01 00:00:00
expires_at: 2020-01-31 23:59:59
is_renewing: true
```

2. I subscribe to a channel as a one-off

```
started_at: 2020-01-01 00:00:00
expires_at: 2020-01-31 23:59:59
is_renewing: false
```

3. I gift one or more subscriptions

```
started_at: 2020-01-01 00:00:00
expires_at: 2020-01-31 23:59:59
is_renewing: false
```

4. I cancel a Subscription and then decide to resume it during the remaining period

```
started_at: 2020-01-01 00:00:00
expires_at: 2020-01-31 23:59:59
is_renewing: false -> true
```

5. I want to cancel my subscription immediately and surrender the remaining time (assuming it's January 16th right now (`2020-01-16 12:13:14`)):

```
started_at: 2020-01-01 00:00:00
expires_at: 2020-01-31 23:59:59 -> now()
is_renewing: true -> false
```

Then, rather than answer the questions with the stored values (e.g: `is_active`) the answers would be derived.

a. is this subscription going to (attempt to) renew at the end of the current period?

`is_renewing = true` and `expires_at > now()`

b. when will the subscription attempt to renew?

`expires_at`

c. has this subscription ended?

`expires_at < now()`

d. how many active subscriptions?

https://github.com/Glimesh/glimesh.tv/blob/3159d105442ffd7432bd393269b656d76fcd65fe/lib/glimesh/payments.ex#L34-L40

```diff
  def list_all_subscriptions do
    Repo.all(
      from s in Subscription,
-        where: s.is_active == true
+        where: s.expires_at > DateTime.utc_now()
    )
    |> Repo.preload([:user, :streamer])
  end
```

---

This should be a small change in practice (rename some fields, update a query, change `Stripe.subscription.delete` to `Stripe.subscription.update`.

ps. A question I haven't attempted to answer here is around the renewal grace period: if Stripe attempts to charge me and it fails, is the subscription cancelled immediately or is Stripe configured to retry payments over the space of a few days?

**Comment by clone1018** [comment]
I think changing the fields to the ones you described makes a lot of sense, and helps support gift subs as well. Sounds like a plan!

> ps. A question I haven't attempted to answer here is around the renewal grace period: if Stripe attempts to charge me and it fails, is the subscription cancelled immediately or is Stripe configured to retry payments over the space of a few days?

I think I still have some confusion around this as well. I kinda hacked in a way to cancel subscriptions using the subscription updated webhook found here: https://github.com/Glimesh/glimesh.tv/blob/dev/lib/glimesh/payments/providers/stripe.ex#L38

Additionally, we do have Stripe setup to retry the subscription:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/226638/104929189-8d326a00-5971-11eb-827c-0d6212fdc502.png">

So after a week of non-payment a subscription is actually cancelled.

**Comment by clone1018** [comment]
This is done now!
